### PR TITLE
Seconds is unnecessary in demo filename

### PR DESCRIPTION
**Pull request by borzaka**
Hours and minutes are enough, and keeps filename shorter.

### CODE REVIEW

**Comment by Technoblazed** [comment]
Disagree with this, bear in mind pugsetup isn't just used for pugs. Seems like a change that isn't needed and is being removed for the sake of removing stuff.

**Comment by borzaka** [comment]
[I suggested](https://github.com/splewis/csgo-pug-setup/commit/d7346686c5288994b51266ff7046b018f9cef180) the minutes and seconds to the demo filename, but in real life, it's looks like the seconds is unnecessary and confusing to read/understand:
`pug_2018-11-21_204441_de_dust2.dem`

`pug_2018-11-21_2044_de_dust2.dem` would be enough I think.

**Comment by splewis** [comment]
I'm fine with removing seconds.

> bear in mind pugsetup isn't just used for pugs.

Well, those use cases aren't really the intended use case. But anyway, it's a cvar default. I prefer to keep the defaults good for the intended private 10man-type use case. Other users can change the cvar value.

(also note that seconds have never been the default in a release, it was added in d7346686c5288994b51266ff7046b018f9cef180)

**Comment by borzaka** [comment]
But do you agree that minutes is needed, and would be a good default?

**Comment by splewis** [comment]
I'm fine with this.

**Pull request merged**
