### PR TITLE
Add specific hint status messages

### PR DESCRIPTION
**Pull request by borzaka**
For: starting pick players, starting match, waiting to start, starting veto process, starting map voting.
No more 9/10 ready hint message when everyone is ready. Fixing issue #256

I was able to compile and test these scenarios: ReadyStatusAllReady, ReadyStatusAllReadyWaiting, ReadyStatusAllReadyVote

### CODE REVIEW

**Comment by splewis** [comment]
I have 2 problems with this:
1) The amount of repetition in the translation phrases
2) Adding in 5 new translation phrases that don't add much value. If this could be restricted to a single "Starting match..." phrase that would be preferable.

**Comment by borzaka** [comment]
I tried to think this thru:
-  "Starting match..." is only a valid hint message in the `CreateCountDown()` function, before that it's just not true. Except one scenario, where autolive, manual teams, and current map settings are used.
- The main idea was that everybody see that 10 out 10 players are ready, and what will happen next (picking players, starting match, waiting to start, map veto process, map voting). I don't like the repetition either, but this makes everything fully understandable.

Maybe if we remove the `{1} out of {2} players are ready\n` part from every new translation phrases? In that case there is no repetition, but we will never see that 10 out of 10 players are ready which I was referring in #256

**Comment by splewis** [comment]
> Maybe if we remove the {1} out of {2} players are ready\n part from every new translation phrases?

I'm fine with that. You can have the same output displayed in the hint text by concatenating the translation phrases, but not requiring so much repetition in the translation files.

**Comment by Technoblazed** [comment]
`PrintHintTextToAll("%t\n%t", "ReadyStatusAllReady", readyPlayers, totalPlayers, "ReadyStatusAllReady");`

Should work

**Pull request merged**
