### PR TITLE
Update maps.txt

### PR DESCRIPTION
**Pull request by kingdragox99**
change train by ancient

### CODE REVIEW

**Comment by crashzk** [comment]
I think it's easier to put all the maps and the user only deletes the maps he doesn't want afterwards.
```
de_dust2
de_mirage
from_hell
de_cble
de_cache
de_overpass
de_nuke
de_train
de_vertigo
de_ancient
```
I believe some like to use all maps, even though not all are on the roadmap these days.

**Comment by splewis** [comment]
I agree, it's preferable to keep all active & recently used maps in the default maplist.  Both train & ancient should be present.

**Comment by kingdragox99** [comment]
That your plugins do what you think is good, I just ask for add ancient bcs
all user maybe don't know how to change map

Le dim. 26 sept. 2021 à 21:02, Sean Lewis ***@***.***> a
écrit :

**Comment by splewis** [comment]
Yes, that comment was just feedback for how to improve the PR.

I went ahead and pushed a change in https://github.com/splewis/csgo-pug-setup/commit/47744980d6c2cee8fb2be349ba0f294f5ab8515c

**Pull request closed without merging**
