### PR TITLE
Update Translation Português-BR

### PR DESCRIPTION
**Pull request by paulocrash**
- Update Translation Português-BR;
~~- Add Map `de_cache` in config `maps.txt`;~~
~~- Add `bot_quota 0` in config `knife.cfg`; **_(For some reason there were moments that went bot in the knife round when some player gave quit, that solved)_**~~

### CODE REVIEW

**Comment by splewis** [comment]
Please only put related changes in a single PR. This is 4 totally unrelated changes.

**Comment by paulocrash** [comment]
Done.

In any case you'd find it interesting to put at least the `de_cache` map in the map list.

**Comment by splewis** [comment]
> In any case you'd find it interesting to put at least the map de_cache in the map list.

That change I didn't intend on merging. 

Can you remove the "#format" lines? They should only be in the english translation. Including it in all the translated files makes changing the use of the phrases harder.

**Comment by paulocrash** [comment]
> Can you remove the "#format" lines? They should only be in the english translation. Including it in all the translated files makes changing the use of the phrases harder.

Done.

**Pull request merged**
